### PR TITLE
Cancel the SF operation on FabricReceiver Drop

### LINKED ISSUE #281: Fabric Sender panic
See run https://github.com/Azure/service-fabric-rs/actions/runs/24022077724/job/70052867379
```
thread 'tokio-rt-worker' (4678) panicked at crates/libs/core/src/sync/channel.rs:174:17:
task should be cancelled when receiver dropped.

thread 'tokio-rt-worker' (4678) panicked at /rustc/e408947bfd200af42db322daf0fadfe7e26d3bd1/library/core/src/panicking.rs:225:5:
panic in a function that cannot unwind
stack backtrace:
```

The problem is that Receiver is not properly cancelled, and we wrongly assumed that caller cannot drop the receiver.

### PR DESCRIPTION
**Pull request by youyuanwu**
Fixes: #281 
It was assumed that user never drops FabricReceiver without cancelling the token. However, this can happen in valid tokio::select branch.
The fix is to remove the send error assert, since there is no correctness problem. This change also auto cancels internal SF operations that is not completed and token not cancelled.

### CODE REVIEW

File: crates/libs/util/src/tokio/tests.rs [hunk 1]
```diff
@@ -773,26 +773,35 @@ mod cancel_token_tests {
...
+            let err = result.expect_err("expected panic");
+            let msg = err
+                .downcast_ref::<&str>()
+                .copied()
+                .or_else(|| err.downcast_ref::<String>().map(|s| s.as_str()))
+                .unwrap_or("");
+            assert!(
+                msg.contains("a callback has already been registered"),
+                "unexpected panic message: {msg}"
+            );
```
[the remark this answers is not in the document]
Comment (youyuanwu) [reply crates/libs/util/src/tokio/tests.rs]: Reverted the change

File: crates/libs/core/src/sync/channel.rs [hunk 2]
```diff
@@ -151,6 +160,21 @@ impl<T> Future for FabricReceiver<T> {
...
+// Cancel the token when the receiver is dropped without having received a value.
+// If nobody is waiting for the result, the operation should be cancelled.
+// This means that SF operation will be auto cancelled if user drops the receiver without waiting for the result.
+impl<T> Drop for FabricReceiver<T> {
+    fn drop(&mut self) {
+        if let Some(t) = self.token.take()
+            && !t.is_cancelled()
+        {
+            t.cancel();
+            // propergate to inner SF ctx, this is needed since rx is no longer polled.
```
[the remark this answers is not in the document]
Comment (youyuanwu) [reply crates/libs/core/src/sync/channel.rs]: Changed to use on_cancel from token to propagate

**Comment by youyuanwu** [comment]
Reverted to the first approach.

File: crates/libs/core/src/sync/channel.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (youyuanwu) [reply crates/libs/core/src/sync/channel.rs]: Reverted back. And documented this is intentional.

File: crates/libs/core/src/sync/channel.rs [hunk 3]
```diff
@@ -164,14 +194,9 @@ impl<T> FabricSender<T> {
...
-            // the work to get the value.
-
-            // receiver should never be dropped if operation is not cancelled.
+            // Receiver's Drop impl cancels the token, so this should always hold.
             if let Some(t) = self.token {
-                debug_assert!(
+                assert!(
                     t.is_cancelled(),
                     "task should be cancelled when receiver dropped."
                 );
```
[the remark this answers is not in the document]
Comment (youyuanwu) [reply crates/libs/core/src/sync/channel.rs]: This is intentional. The sender and receiver has this contract.

File: crates/libs/core/src/sync/proxy.rs [hunk 4]
```diff
@@ -29,13 +29,16 @@ use super::{FabricReceiver, oneshot_channel};
...
+/// Cancelling the token will in turn cancel the fabric operation.
 /// After cancellation is triggered, the receiver future should finish in a short time,
-/// with an error code opeartion cancelled, or other code if cancel failed.
+/// with an error code operation cancelled, or other code if cancel failed.
 /// If the result is ready before the cancellation is triggered, the success result will
 /// be the output of the receiver future.
+///
+/// Cancellation best practice:
+/// User should always poll the receiver future to completion even after cancellation is triggered,
+/// to ensure the cancellation signal is properly propagated to SF and resources are cleaned up in a timely manner.
```
[the remark this answers is not in the document]
Comment (youyuanwu) [reply crates/libs/core/src/sync/proxy.rs]: PR description fixed.

File: crates/libs/core/src/sync/channel.rs [hunk 5]
```diff
@@ -19,14 +19,14 @@ use crate::{
 pub use futures_channel::oneshot::{self, Receiver, Sender};
 
 // Token that wraps oneshot receiver.
-// The future recieve does not have error. This is designed for the use
+// The future receive does not have error. This is designed for the use
```
Comment (jrahman) [inline crates/libs/core/src/sync/channel.rs]: future receiver?

File: crates/libs/core/src/sync/channel.rs [hunk 6]
```diff
@@ -19,14 +19,14 @@ use crate::{
...
 // case where SF guarantees that sender will be called.
```
Comment (jrahman) [inline crates/libs/core/src/sync/channel.rs]: Does the new Drop impl invalidate this?

File: crates/libs/core/src/sync/channel.rs [hunk 7]
```diff
@@ -100,12 +106,16 @@ impl<T> Future for FabricReceiver<T> {
...
-            (Poll::Ready(Ok(data)), _) => Poll::Ready(Ok(data)),
+            (Poll::Ready(Ok(data)), _) => {
+                // Result received successfully; clear the token so Drop
+                // does not cancel the operation.
+                this.clear_cancel_fields();
+                Poll::Ready(Ok(data))
+            }
             (Poll::Ready(Err(_)), Some(t)) => {
                 if t.is_cancelled() {
                     // clear the token since we only propergate the signal once.
```
Comment (qbradley) [inline crates/libs/core/src/sync/channel.rs]: s/propergate/propagate/

Comment (qbradley) [reply crates/libs/core/src/sync/channel.rs]: and a few other places in the file

**Review by qbradley — APPROVED** [review]
s/propergate/propagate/

File: crates/libs/core/src/sync/channel.rs [hunk 8]
```diff
@@ -151,6 +160,27 @@ impl<T> Future for FabricReceiver<T> {
...
+        // Note that there is a chance that SF operation is not cancelled when user cancelled the token
+        // and drop the receiver immediately without polling the receiver future.
+        // because the cancellation signal is only propagated when polling the receiver future.
+        // However this very uncommon and violate the best practice that user should always poll
+        // the receiver future to completion even after the cancellation is triggered.
+        // SF operation will be left in the background and eventually finish.
+        if let Some(t) = self.token.take()
+            && !t.is_cancelled()
+        {
+            t.cancel();
```
Comment (jrahman) [inline crates/libs/core/src/sync/channel.rs]: It makes sense why cancel_inner_ctx() is called, but isn't `t` the user supplied cancellation token from further up the stack? Couldn't that cancellation token be shared with other pending futures that would be cancelled as a side-effect of this future being dropped, do we want that?

Comment (youyuanwu) [reply crates/libs/core/src/sync/channel.rs]: Good point. I may need to create a new token that is chained to the user's token, but only cancel this new token,

File: crates/libs/core/src/sync/channel.rs (hunk 6 above)
Comment (youyuanwu) [reply crates/libs/core/src/sync/channel.rs]: Updated the comments

File: crates/libs/core/src/sync/channel.rs (hunk 8 above)
Comment (youyuanwu) [reply crates/libs/core/src/sync/channel.rs]: Changed to never cancel user token.
