### PR TITLE
Safe wrapping for MustCatchup field in FABRIC_REPLICA_INFORMATION_EX1

### LINKED ISSUE #39: PrimaryReplictorProxy crashes on build_replica()
Build replica crashed in SF runtime.
```rs
async fn build_replica(&self, replica: &ReplicaInfo) -> ::windows_core::Result<()>;
```
The problem is that the MustCatchup field is not correctly propagated from proxy layer into BeginBuildReplica c function.
This affects only apps using PrimaryReplicatorProxy.

### PR DESCRIPTION
**Pull request by youyuanwu**
Fixes #39

### CODE REVIEW

File: crates/libs/core/src/runtime/stateful_types.rs [hunk 1]
```diff
@@ -129,88 +133,134 @@ impl From<FABRIC_REPLICA_STATUS> for ReplicaStatus {
...
             CatchUpCapability: r.CatchUpCapability,
+            MustCatchUp: must_catchup,
         }
     }
 }
 
 impl ReplicaInfo {
-    pub fn get_raw(&self) -> FABRIC_REPLICA_INFORMATION {
-        FABRIC_REPLICA_INFORMATION {
+    // The parts has the same lifetime as self.
```
Comment (jrahman) [inline crates/libs/core/src/runtime/stateful_types.rs:247]: nit
```suggestion
    // The parts have the same lifetime as self.
```

File: crates/libs/core/src/runtime/stateful_types.rs [hunk 2]
```diff
@@ -129,88 +133,134 @@ impl From<FABRIC_REPLICA_STATUS> for ReplicaStatus {
...
+    // Caller needs to stitch the parts together.
```
Comment (jrahman) [inline crates/libs/core/src/runtime/stateful_types.rs:248]: nit: What does "stitch the parts together" mean here? From background conversations, FABRIC_REPLICA_INFORMATION::Reserved needs to point at FABRIC_REPLICA_INFORMATION_EX1, but would not be immediately obvious to a fresh reader

**Review by jrahman — APPROVED** [review]

**Review by rsajwani — APPROVED** [review]

File: crates/libs/core/src/runtime/stateful_types.rs (hunk 2 above)
Comment (youyuanwu) [reply crates/libs/core/src/runtime/stateful_types.rs]: Added the details.
